# project.yaml
staging-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://rpc.sepolia.org
    - chain-name: avalanche-testnet-fuji
      url: https://api.avax-test.network/ext/bc/C/rpc
